apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: k8-first
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer

# Commands:
# kubectl apply -f service.yaml
# minikube service backend
