version: "3.8"
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - ./volumes/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 2

  python:
    build:
      context: .
    volumes:
      - ./src/:/usr/app/src/
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
