version: "3.8"

services:
    minio:
        image: minio/minio
        volumes:
            - /data
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
        ports:
            - "9100:9000"
            - "9101:9001"
        command: server --console-address ":9001" /data

    create-bucket:
        image: minio/mc
        depends_on:
            - minio
        entrypoint: /bin/sh -c
        command:
            - >
                /bin/sh -c "
                echo 'Waiting for MinIO server to start...' &&
                sleep 10 &&
                mc alias set minio http://minio:9000 minio minio123 &&
                mc mb minio/dev &&
                mc anonymous set public minio/dev &&
                exit 0
                "
